name: Ansible App deploy
'on':
  workflow_dispatch:
    inputs:
      App_Name:
        description: App Name
        default: Please type here the application name
        required: true
      Image:
        type: choice
        description: Image-OS
        options:
          - debian11_apache2_4_mysql8_node16_php8_1
          - debian11_apache2_4_php8_1-drupal9_4_7
        required: true
        default: Please choice the image ID below
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  credentials_build_deploy:
    name: Building and Pushing the Image
    runs-on: [self-hosted, staging] ## private runner
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Print the Application Name
      run: echo "Hello ${{ github.event.inputs.App_Name }}"
    - name: Print the Image tag
      run: echo "Hello ${{ github.event.inputs.Image }}"
