name: Ansible App deploy

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'App Name'
        default: 'hive-v3'
        required: true
	    name:
        type: choice
        description: Image 
        options: 
        - debian11_apache2_4_mysql8_node16_php8_1
        - debian11_apache2_4_php8_1-drupal9_4_7
		    - lautaro Martinez
