name: Ansible App deploy
'on':
  workflow_dispatch:
    inputs:
      name:
        description: App Name
        default: hive-v3
        required: true
      name2:
        type: choice
        description: Image
        options:
          - debian11_apache2_4_mysql8_node16_php8_1
          - debian11_apache2_4_php8_1-drupal9_4_7
          - lautaro Martinez
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
